CREATE TABLE TBL_QL_GV_BC
(	
	ten1 NVARCHAR(30) NOT NULL,
	sdt1 VARCHAR(20) PRIMARY KEY NOT NULL,
	donVi1 NVARCHAR(30) NOT NULL,
	namVe1 INT NOT NULL,
	heSoLuong FLOAT NOT NULL
)

CREATE TABLE TBL_QL_GV_MG
(	
	ten2 NVARCHAR(30) NOT NULL,
	sdt2 VARCHAR(20) PRIMARY KEY NOT NULL,
	donVi2 NVARCHAR(30) NOT NULL,
	namVe2 INT NOT NULL,
	soGioGiang FLOAT NOT NULL
)